on:
  push:
    branches: 
    - main
jobs:
  build:
    runs-on: windows-latest
    permissions: 
      id-token: write
      pages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            dist/
          key: ${{ runner.os }}-{{ github.sha }}

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build Atuin Powershell PR
        run: |
          cargo install --git https://github.com/ltrzesniewski/atuin.git --branch powershell-pr
          mkdir -p ./dist
          7z a dist/atuin.zip $Env:USERPROFILE/.cargo/bin/atuin.exe

      - name: Generate installation script  
        shell: bash
        run: |
          mkdir -p ./dist 
          cat << 'EOF' > ./dist/install.ps1
          winget install --id Git.Git
          git clone https://github.com/izzalDev/dotfiles-new "$Env:USERPROFILE\.config"
          & "$Env:USERPROFILE\.config\install.ps1"
          EOF

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "dist"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
